name: Django CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.14,3.11,3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Conda environment with Micromamba
      uses:  mamba-org/provision-with-micromamba@main
      with:
        cache-downloads: true
        channels: "conda-forge,defaults"
        environment-file: environment.yml
        environment-name: filterBoa
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Conda info
      shell: bash -el {0}
      run: conda info
    - name: Conda list
      shell: pwsh
      run: conda list
    - name: Environment
      shell: bash -el {0}
      run: printenv | sort    
    - name: Run Tests
      shell: bash -el {0}
      run: |
        cd src 
        python manage.py test